name: Fast forward merge PR

on:
  schedule:
    - cron: "0,15,30,45 * * * *"

jobs:
  fast_forward_merge:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - env:
          REPOSITORY: ${{ github.repository}}
        run: |
          branch=$(gh pr status -R $REPOSITORY --json headRefName,mergeStateStatus --jq '.createdBy | map(select(.mergeStateStatus == "CLEAN")) | .[-1].headRefName')
          if [ -n "$branch" ]; then
            git rebase --ff-only "$branch"
          fi
