name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          bump-minor-pre-major: true
          package-name: workflow-test
          release-type: go
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
